---
- name: Installing apache on centos
  import_tasks: redhat_install.yml
  when: ansible_distribution == 'CentOS' or ansible_os_family == "RedHat" or ansible_os_family == "Amazon"

- name: Installing apache on debian
  import_tasks: ubuntu_install.yml
  when: ansible_distribution == 'Ubuntu'

- name: copying the config file
  import_tasks: config.yml

- name: Starting and enabling service of apache
  import_tasks: service.yml
