---
- name: starting and enabling the service
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == 'CentOS' or ansible_os_family == "RedHat" or ansible_os_family == "Amazon"

- name: starting and enabling the service
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution == 'Ubuntu'

